apps/main_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout'),
]

loginReg/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.main_app.urls', namespace = 'users')),
]

apps/main_app/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def add_user(self, postData):
        errors = []
        if not len(postData['first_name']) > 2:
            errors.append('First name must be be at least 2 characters!')
        if not len(postData['last_name']):
            errors.append('Last name must be there!')
        if not len(postData['email']):
            errors.append('Email must be there')
        if not EMAIL_REGEX.match(postData['email']):
            errors.append('Must have a valid email')
        if len(postData['password']) < 8:
            errors.append('Password must be at least 8 characters long!')
        if not postData['password'] == postData['confirm_password']:
            errors.append('Passwords must match!')

        user = self.filter(email = postData['email'])

        if user:
            errors.append('Email already exists!')

        modelResponse = {}
        # if failed validations
        if errors:
            modelResponse['status'] = False
            modelResponse['errors'] = errors
        # passed validations, save user
        else:
            hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], password = hashed_password)

            modelResponse['status'] = True
            modelResponse['user'] = user

        # send modelResponse to views.py
        return modelResponse

    def check_user(self, postData):
        errors = []
        user = self.filter(email = postData['email'])
        # check to see is in db
        modelResponse = {}
        if user[0]:
            # check for passwords
            if not bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()):
                errors.append('Invalid email/password combination!')
            # success login
            else:
                modelResponse['status'] = True
                modelResponse['user_id'] = user[0].id
        else:
            errors.append('Invalid email')

        if errors:
            modelResponse['status'] = False
            modelResponse['errors'] = errors

        return modelResponse

class User(models.Model):
    first_name = models.CharField(max_length = 45)
    last_name = models.CharField(max_length = 45)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/main_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'main_app/index.html')

def register(request):
    if request.method == 'POST':
        print request.POST
        response_from_models = User.objects.add_user(request.POST)
        # if failed validations
        if not response_from_models['status']:
            for error in response_from_models['errors']:
                messages.error(request, error)
            return redirect('users:index')
        # if true on validations
        else:
            request.session['user_id'] = response_from_models['user'].id
            return redirect('users:success')
    else:
        return redirect('users:index')

def login(request):
    response_from_models = User.objects.check_user(request.POST)
    if not response_from_models['status']:
        for error in response_from_models['errors']:
            messages.error(request, error)
        return redirect('users:index')
    else:
        request.session['user_id'] = response_from_models['user_id']
        return redirect('users:success')

def success(request):
    if not 'user_id' in request.session:
        messages.error(request, 'Must be logged in!')
        return redirect('users:index')
    return render(request, 'main_app/success.html')

def logout(request):
    request.session.clear()
    return redirect('users:index')

apps/main_app/templates/main_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Registration</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'main_app/style/index.css' %}" media="screen" title="no title">
  </head>
  <body>
    <div class="container">
      <div class="main_content">
        {% if messages %}
          {% for message in messages %}
            <p>{{ message }}</p>
          {% endfor %}
        {% endif %}
        <div class="registration">
          <fieldset>
            <legend>Register</legend>
            <form class="" action="{% url 'users:register' %}" method="post">
              {% csrf_token %}
              <p>
                First Name
                <input type="text" name="first_name" value="">
              </p>
              <p>
                Last Name
                <input type="text" name="last_name" value="">
              </p>
              <p>
                Email
                <input type="text" name="email" value="">
              </p>
              <p>
                Password
                <input type="password" name="password" value="password">
              </p>
              <p>
                Password Confirmation
                <input type="password" name="confirm_password" value="password">
              </p>
              <input type="submit" name="submit" value="Register">
            </form>
          </fieldset>
        </div><!-- end_of_regristration-->
        <div class="login">
          <fieldset>
            <legend>Login</legend>
            <form class="" action="{% url 'users:login' %}" method="post">
              {% csrf_token %}
              <p>
                Email
                <input type="email" name="email" value="">
              </p>
              <p>
                Password
                <input type="password" name="password" value="password">
              </p>
              <input type="submit" name="submit" value="Login">
            </form>
          </fieldset>
        </div><!-- end_of_login-->
      </div><!-- end_of_main_content -->
    </div><!-- end_of_container-->
  </body>
</html>

apps/main_app/templates/main_app/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success Page</title>
  </head>
  <body>
    <div class="container">
      <h1>Welcome to the success page!</h1>
      {{ request.session.user_id }}
      <form class="" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" name="submit" value="Logout">
      </form>
    </div><!-- end_of_container-->
  </body>
</html>